/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Asgeir' at '10/30/15 7:12 PM' with Gradle 2.8
 *
 * @author Asgeir, @date 10/30/15 7:12 PM
 */

import  edu.princeton.cs.introcs.*;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}



public class Human{
    public void makeMove()
    {
        StdOut.printf("")
    }
}